---

- name: Ensure metabase service is defined
  template: src="templates/upstart.conf.j2" dest="/etc/init/metabase.conf" owner=root group=root mode=0644
  when: ansible_os_family == "Debian"
  tags: [upstart]
  notify:
    - restart metabase

- name: Ensure metabase service state is defined
  service: name=metabase state="{{ metabase_state }}" enabled="{{ metabase_enabled }}"
  notify:
    - restart metabase
